const APP_LOADING = 'APP_LOADING';
const INITIAL_UNIT_DATA = 'INITIAL_UNIT_DATA';
const INITIAL_FILTER_DATA = 'INITIAL_FILTER_DATA';
const UNIT_DATA_IS_LOADING = 'UNIT_DATA_IS_LOADING';
const CHANGE_RANGE_VALUE= 'CHANGE_RANGE_VALUE';
const CHANGE_FILTER_VALUE= 'CHANGE_FILTER_VALUE';

export {
    APP_LOADING,
    INITIAL_UNIT_DATA,
    INITIAL_FILTER_DATA,
    UNIT_DATA_IS_LOADING,
    CHANGE_RANGE_VALUE,
    CHANGE_FILTER_VALUE
};
